smpRegionName: test69
axeRegionName: test69
netheritepotRegionName: test69
tankRegionName: test69
crystalpvpRegionName: test69
diamodpotRegionName: test69
UHCRegionName: test69
CartPVPRegionName: test69
